server:
  port: 2333

lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: false
      soundcloud: true
      bandcamp: true
      twitch: true
      vimeo: true
      http: true
      local: false

  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.0"
      repository: "https://maven.lavalink.dev/releases"

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true

    remoteCipher:
      url: "https://cipher.kikkia.dev/"

    clients:
      - MUSIC
      - ANDROID_VR
      - WEB
      - WEBEMBEDDED

logging:
  level:
    root: INFO
    lavalink: INFO
    dev.lavalink.youtube: DEBUG